export const imageFallbacks = {
  logo: "/images/logo/fallback.svg",
  hero: "/images/hero/fallback.svg",
  projects: "/images/projects/fallback.svg",
  layouts: "/images/layouts/fallback.svg",
  styles: "/images/styles/fallback.svg",
  materials: "/images/materials/fallback.svg",
  production: "/images/production/fallback.svg",
  cta: "/images/cta/fallback.svg",
} as const;

export const imageUsageRules = {
  component: "next/image",
  heroPreload: true,
  belowFoldLoading: "lazy",
  realProjectLabel: "реализованный проект",
  exampleProjectLabel: "пример исполнения",
} as const;

export const imageMap = {
  logo: {
    main: "/images/logo/kit-logo.svg",
    mainPng: "/images/logo/kit-logo.png",
    icon: "/images/logo/kit-icon.svg",
    iconFramed: "/images/logo/kit-icon-framed.svg",
    alt: "Логотип КИТ Кухни",
    iconAlt: "Знак кухонной компании КИТ",
    iconFramedAlt: "Знак КИТ в рамке",
    fallback: imageFallbacks.logo,
  },

  hero: {
    image: "/images/hero/hero-dark-premium-kitchen.png",
    alt: "Современная кухня на заказ КИТ с тёмными фасадами, деревом и каменной столешницей",
    preload: true,
    sizes: "(max-width: 768px) 100vw, (max-width: 1280px) 50vw, 640px",
    fallback: imageFallbacks.hero,
  },

  projects: [
    {
      id: "harmony-primorsky",
      title: "Кухня «Гармония»",
      district: "Приморский район",
      area: "12,4 м²",
      style: "Современная",
      layout: "Угловая",
      priceFrom: "от 245 000 ₽",
      image: "/images/projects/project-harmony-primorsky.png",
      alt: "Современная угловая кухня Гармония в Приморском районе",
      isRealProject: false,
      label: "пример исполнения",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.projects,
    },
    {
      id: "scandi-vasileostrovsky",
      title: "Кухня «Сканди»",
      district: "Василеостровский район",
      area: "10,8 м²",
      style: "Скандинавская",
      layout: "Прямая",
      priceFrom: "от 198 000 ₽",
      image: "/images/projects/project-scandi-vasileostrovsky.png",
      alt: "Скандинавская кухня Сканди в Василеостровском районе",
      isRealProject: false,
      label: "пример исполнения",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.projects,
    },
    {
      id: "light-kalininsky",
      title: "Кухня «Лайт»",
      district: "Калининский район",
      area: "9,6 м²",
      style: "Современная",
      layout: "Кухня до потолка",
      priceFrom: "от 175 000 ₽",
      image: "/images/projects/project-light-kalininsky.png",
      alt: "Светлая современная кухня Лайт в Калининском районе",
      isRealProject: false,
      label: "пример исполнения",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.projects,
    },
    {
      id: "elegance-moskovsky",
      title: "Кухня «Элеганс»",
      district: "Московский район",
      area: "13,2 м²",
      style: "Неоклассика",
      layout: "Угловая",
      priceFrom: "от 262 000 ₽",
      image: "/images/projects/project-elegance-moskovsky.png",
      alt: "Неоклассическая кухня Элеганс в Московском районе",
      isRealProject: false,
      label: "пример исполнения",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.projects,
    },
    {
      id: "graphite-petrogradsky",
      title: "Кухня «Графит»",
      district: "Петроградский район",
      area: "11,5 м²",
      style: "Лофт",
      layout: "С островом",
      priceFrom: "от 228 000 ₽",
      image: "/images/projects/project-graphite-petrogradsky.png",
      alt: "Тёмная графитовая кухня в Петроградском районе",
      isRealProject: false,
      label: "пример исполнения",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.projects,
    },
    {
      id: "walnut-kudrovo",
      title: "Кухня «Волнат»",
      district: "Кудрово",
      area: "14,1 м²",
      style: "Современная",
      layout: "П-образная",
      priceFrom: "от 270 000 ₽",
      image: "/images/projects/project-walnut-kudrovo.png",
      alt: "Современная кухня с древесной текстурой в Кудрово",
      isRealProject: false,
      label: "пример исполнения",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.projects,
    },
  ],

  layouts: [
    {
      title: "Угловые кухни",
      image: "/images/layouts/layout-corner-kitchen.png",
      alt: "Угловая кухня на заказ",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.layouts,
    },
    {
      title: "Прямые кухни",
      image: "/images/layouts/layout-straight-kitchen.png",
      alt: "Прямая кухня на заказ",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.layouts,
    },
    {
      title: "Кухни до потолка",
      image: "/images/layouts/layout-ceiling-kitchen.png",
      alt: "Кухня до потолка с большим количеством мест хранения",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.layouts,
    },
    {
      title: "Кухни с островом",
      image: "/images/layouts/layout-island-kitchen.png",
      alt: "Кухня с островом на заказ",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.layouts,
    },
  ],

  styles: [
    {
      title: "Современные",
      image: "/images/styles/style-modern-kitchen.png",
      alt: "Современная кухня на заказ",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.styles,
    },
    {
      title: "Скандинавские",
      image: "/images/styles/style-scandinavian-kitchen.png",
      alt: "Скандинавская кухня на заказ",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.styles,
    },
    {
      title: "Неоклассика",
      image: "/images/styles/style-neoclassical-kitchen.png",
      alt: "Кухня в стиле неоклассика",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.styles,
    },
    {
      title: "Лофт",
      image: "/images/styles/style-loft-kitchen.png",
      alt: "Кухня в стиле лофт",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.styles,
    },
  ],

  materials: [
    {
      title: "Фасады МДФ",
      image: "/images/materials/material-mdf-facades.png",
      alt: "Образцы фасадов МДФ для кухни",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.materials,
    },
    {
      title: "Столешницы",
      image: "/images/materials/material-stone-countertop.png",
      alt: "Образцы столешниц для кухни",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.materials,
    },
    {
      title: "Фурнитура",
      image: "/images/materials/material-hardware-hinges.png",
      alt: "Петли и выдвижные механизмы для кухни",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.materials,
    },
    {
      title: "Корпус ЛДСП",
      image: "/images/materials/material-ldsp-body.png",
      alt: "ЛДСП для корпуса кухни",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 25vw",
      fallback: imageFallbacks.materials,
    },
  ],

  production: [
    {
      title: "Производственный цех",
      image: "/images/production/production-workshop.png",
      alt: "Производственный цех для изготовления кухонь",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.production,
    },
    {
      title: "Материалы",
      image: "/images/production/production-materials.png",
      alt: "Материалы для производства кухонь",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.production,
    },
    {
      title: "Сборка",
      image: "/images/production/production-assembly.png",
      alt: "Сборка кухонных корпусов в цеху",
      loading: "lazy",
      sizes: "(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw",
      fallback: imageFallbacks.production,
    },
  ],

  cta: {
    illustration: "/images/cta/kit-kitchen-line-art-teal.png",
    alt: "Линейная иллюстрация кухни",
    loading: "lazy",
    sizes: "(max-width: 768px) 100vw, 520px",
    fallback: imageFallbacks.cta,
  },
} as const;

export type ProjectImage = (typeof imageMap.projects)[number];

export function getProjectBadge(project: { isRealProject: boolean; label?: string }) {
  return project.isRealProject
    ? imageUsageRules.realProjectLabel
    : project.label ?? imageUsageRules.exampleProjectLabel;
}

export default imageMap;
