import type { DirectionPage, DistrictPage } from "@/types/content";

export const districtPages: DistrictPage[] = [
  {
    slug: "kuhni-murino",
    title: "Кухни на заказ в Мурино",
    description: "Подберём планировку кухни под размеры квартиры или дома в Мурино и подготовим предварительный расчёт.",
    details: ["Учитываем особенности помещения, хранение, технику и удобство ежедневного использования.", "Показываем релевантные примеры и честно отделяем их от реальных проектов."],
    cta: "Рассчитать кухню в Мурино",
    relatedProjectIds: ["walnut-kudrovo", "light-kalininsky"],
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухни на заказ в Мурино — КИТ",
    seoDescription: "Кухни на заказ в Мурино: предварительный расчёт, подбор планировки и материалов.",
  },
  {
    slug: "kuhni-kudrovo",
    title: "Кухни на заказ в Кудрово",
    description: "Поможем рассчитать кухню для квартиры в Кудрово: от компактной прямой планировки до кухни с расширенным хранением.",
    details: ["Сначала обсуждаем задачу и ориентировочный бюджет.", "После замера и проекта фиксируем состав работ и итоговую стоимость."],
    cta: "Рассчитать кухню в Кудрово",
    relatedProjectIds: ["walnut-kudrovo", "harmony-primorsky"],
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухни на заказ в Кудрово — КИТ",
    seoDescription: "Кухни на заказ в Кудрово: предварительный расчёт, проектные решения и сборка.",
  },
  {
    slug: "kuhni-vsevolozhsk",
    title: "Кухни на заказ во Всеволожске",
    description: "Рассчитаем кухню для квартиры или дома во Всеволожске с учётом планировки, материалов и условий доставки.",
    details: ["Условия замера и доставки уточняются у менеджера.", "Итоговая стоимость зависит от проекта, материалов и фурнитуры."],
    cta: "Рассчитать кухню во Всеволожске",
    relatedProjectIds: ["scandi-vasileostrovsky", "elegance-moskovsky"],
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухни на заказ во Всеволожске — КИТ",
    seoDescription: "Кухни на заказ во Всеволожске: консультация, предварительный расчёт и проект.",
  },
  {
    slug: "kuhni-pushkin",
    title: "Кухни на заказ в Пушкине",
    description: "Подготовим предварительный расчёт кухни в Пушкине и поможем выбрать практичную планировку под ваш сценарий.",
    details: ["Можно начать с фото помещения, размеров или короткой консультации.", "Точная стоимость определяется после замера, выбора материалов и проекта."],
    cta: "Рассчитать кухню в Пушкине",
    relatedProjectIds: ["elegance-moskovsky", "light-kalininsky"],
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухни на заказ в Пушкине — КИТ",
    seoDescription: "Кухни на заказ в Пушкине: подбор планировки, материалов и ориентировочной стоимости.",
  },
];

export const directionPages: DirectionPage[] = [
  {
    slug: "uglovye-kuhni-spb",
    title: "Угловые кухни на заказ в СПб",
    description: "Угловая кухня помогает задействовать две стены и собрать удобный рабочий треугольник даже в сложном помещении.",
    details: ["Подходит для квартир, студий и кухонь-гостиных.", "Предварительный расчёт зависит от размеров, фасадов, столешницы и фурнитуры."],
    cta: "Рассчитать угловую кухню",
    relatedProjectIds: ["harmony-primorsky", "elegance-moskovsky"],
    layoutType: "Угловая",
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Угловые кухни на заказ в СПб — КИТ",
    seoDescription: "Угловые кухни на заказ в СПб: подбор планировки и предварительный расчёт.",
  },
  {
    slug: "pryamye-kuhni-spb",
    title: "Прямые кухни на заказ в СПб",
    description: "Прямая кухня подходит для компактных, вытянутых помещений и случаев, когда важно сохранить свободную зону.",
    details: ["Поможем рассчитать хранение, рабочую поверхность и место для техники без перегруза пространства."],
    cta: "Рассчитать прямую кухню",
    relatedProjectIds: ["scandi-vasileostrovsky"],
    layoutType: "Прямая",
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Прямые кухни на заказ в СПб — КИТ",
    seoDescription: "Прямые кухни на заказ в СПб: компактные решения и предварительный расчёт.",
  },
  {
    slug: "kuhni-do-potolka",
    title: "Кухни до потолка",
    description: "Кухня до потолка помогает добавить хранение и визуально собрать интерьер без лишних зазоров сверху.",
    details: ["На консультации обсудим высоту, антресоли, доступ к верхним модулям и удобство ухода."],
    cta: "Рассчитать кухню до потолка",
    relatedProjectIds: ["light-kalininsky"],
    layoutType: "Кухня до потолка",
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухни до потолка — КИТ",
    seoDescription: "Кухни до потолка на заказ: хранение, антресоли и предварительный расчёт.",
  },
  {
    slug: "kuhni-s-ostrovom",
    title: "Кухни с островом",
    description: "Кухня с островом подходит для просторных помещений, где важны рабочая поверхность, хранение и место общения.",
    details: ["Проверяем проходы, расположение коммуникаций и удобство сценариев до финального проекта."],
    cta: "Рассчитать кухню с островом",
    relatedProjectIds: ["graphite-petrogradsky"],
    layoutType: "С островом",
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухни с островом — КИТ",
    seoDescription: "Кухни с островом на заказ: планировка, коммуникации и предварительный расчёт.",
  },
  {
    slug: "kuhni-v-rassrochku",
    title: "Кухни в рассрочку",
    description: "Можно обсудить оплату частями и подобрать вариант кухни под комфортный бюджет без преждевременных обещаний.",
    details: ["Условия рассрочки уточняются у менеджера.", "Итоговая стоимость фиксируется после проекта и согласования материалов."],
    cta: "Уточнить условия оплаты",
    relatedProjectIds: ["harmony-primorsky", "light-kalininsky"],
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухни в рассрочку — КИТ",
    seoDescription: "Кухни в рассрочку: варианты оплаты частями и предварительный расчёт.",
  },
  {
    slug: "kuhnya-dlya-studii",
    title: "Кухня для студии",
    description: "Для студии важно совместить хранение, рабочую зону и аккуратный переход к жилому пространству.",
    details: ["Подберём планировку, фасады и материалы так, чтобы кухня не перегружала интерьер."],
    cta: "Рассчитать кухню для студии",
    relatedProjectIds: ["scandi-vasileostrovsky", "light-kalininsky"],
    isDraft: true,
    hasUniqueContent: false,
    approved: false,
    seoTitle: "Кухня для студии — КИТ",
    seoDescription: "Кухни для студий на заказ: компактные планировки и предварительный расчёт.",
  },
];
